package hibernate;
// Generated 30-ene-2015 9:24:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Inmueble generated by hbm2java
 */
public class Inmueble  implements java.io.Serializable {


     private Integer id;
     private String localidad;
     private String direccion;
     private Integer tipo;
     private Integer habitaciones;
     private Float precio;
     private String usuario;
     private Set fotos = new HashSet(0);

    public Inmueble() {
    }

    public Inmueble(String localidad, String direccion, Integer tipo, Integer habitaciones, Float precio, String usuario, Set fotos) {
       this.localidad = localidad;
       this.direccion = direccion;
       this.tipo = tipo;
       this.habitaciones = habitaciones;
       this.precio = precio;
       this.usuario = usuario;
       this.fotos = fotos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public Integer getHabitaciones() {
        return this.habitaciones;
    }
    
    public void setHabitaciones(Integer habitaciones) {
        this.habitaciones = habitaciones;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Set getFotos() {
        return this.fotos;
    }
    
    public void setFotos(Set fotos) {
        this.fotos = fotos;
    }




}


